general:
    test: True
    verbose: True

local_features:
    features_name: superpoint # choices=['superpoint', 'aliked']
    superpoint:
        resize_width: 1280 # tested with 640
        resize_height: 960 # tested with 480
        do_resize: True
    aliked:
        model_name: "aliked-n16rot" # choices=['aliked-t16', 'aliked-n16', 'aliked-n16rot', 'aliked-n32'], default="aliked-n16rot"
        top_k: 500
        scores_th: 0.2
        n_limit: 5000

mapping:
    sliding_window: 10 # tested with 10
    max_match_distance: 5
    max_keyframes: 1000000
    method: "custom" # choices=['with_pycolmap_reconstruct', 'custom']