general:
    test: True
    verbose: True

local_features:
    features_name: aliked # choices=['superpoint', 'aliked']
    superpoint:
        resize_width: 752
        resize_height: 480
        do_resize: True
    aliked:
        model_name: "aliked-n16rot" # choices=['aliked-t16', 'aliked-n16', 'aliked-n16rot', 'aliked-n32'], default="aliked-n16rot"
        top_k: 500
        scores_th: 0.2
        n_limit: 5000

mapping:
    cameras: ["cam0", "cam1"] # Both monocular and multiview are supported
    rig_match_rule:
        - ["cam0", "cam1"]
    cameras_for_baseline_estim: ["cam0", "cam1"]
    start_frame: 10
    baseline: 0.110078
    sliding_window: 10
    max_match_distance: 0.2
    max_keyframes: 10000000
    method: "custom" # choices=['with_pycolmap_reconstruct', 'custom']